---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stasich
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        fakeLabel: v3
    spec:
      volumes:
      - name: config
        configMap:
          name: nginx-config-map
      containers:
      - image: nginx:1.18-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: false
      restartPolicy: Always

---        
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
  namespace: stasich
data:
  default.conf: |    
    server {
      listen       80 default_server;
      index index.php;
      server_name  _;
      default_type text/plain;
    
      location / {
          return 200 '$hostname\n';
      }
    }
---        
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: stasich
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    app: nginx
